### ISSUE TITLE
6+MB SA-1 rom not loading

### ISSUE THREAD

**Issue by MandL27** [bubble2k16/snes9x_3ds#13]
When I try to load a 6MB SA-1 rom in the emulator, it gets stuck in an endless loop of printing `R: ` followed by an incrementing hex value from about 0x2200 to 0x2FFF. This is, functionally speaking, a softlock. The rom works just fine on current desktop builds of snes9x, so it isn't an issue with the rom itself.

**Comment by bubble2k16** [comment]
Hi, can you let me know which ROM it was?

**Comment by MandL27** [comment]
It was a hack of Super Mario World. [This one](https://www.smwcentral.net/?p=section&a=details&id=14812), to be specific.

**Comment by bubble2k16** [comment]
I don't normally support game patches/ hacks since some of them rely on bugs / features on future versions of emulators. Wonder Project J (English) was once such example, which I managed to fix. I'll look into this only when I really really have the time, so it's going to be low priority. :) But I'll keep this issue open.

**Comment by MandL27** [comment]
I bring it up mostly because the SA-1 chip can, even on hardware iirc, support rom sizes up to 8 megs. It's just that no games released ever used that, and so it went unnoticed by most emulators until recently. Both 1.54 and FuSoYa's fork of 1.53 support it, if their code would be of any help when you are able to implement it.

**Comment by bubble2k16** [comment]
I understand. It might just be some bugs in Snes9x v1.43 or v1.53 that makes it work in one version and not the other. I'll have a look if time allows.

**Comment by MandL27** [comment]
In other news, I did a bit of digging and found that apparently there were some six-meg commercial SNES games. I could see if they similarly break.

**Comment by bubble2k16** [comment]
Hmm... It sounds like it could really be the way the ROM size is calculated that breaks the way the emulator accesses data. Will look into it some time later. :)

**Comment by MandL27** [comment]
Late, but that sounds like a fairly feasible explanation for why I got the `R: 0x2220` to `R: 0x2FFF` infinite loop. If I'm understanding this right, it was trying to index the ROM, but the size made the indexer not behave as planned, thus creating an infinite loop.

**Comment by bubble2k16** [comment]
Actually I found the bug. Apparently the version 1.43 mapped the SA-1 MMC (whatever that is) wrongly, causing the game to run instructions in the wrong memory locations very very early into boot. 

That has since been fixed in the latest nightly build. You can try to get the latest .3dsx/.cia from the Github's source code listing. I've tested and at least VLDC9 can be played now. 

So it's not really a problem with 6MB ROMs - by the way Tales of Phantasia and Star Ocean are 6MB ROMs and they work fine. :)

**Comment by bubble2k16** [comment]
Alright, the latest release v1.10 will allow you to play VLDC 9. Thanks! :)
