### ISSUE TITLE
Save Sync with Dropbox?

### ISSUE THREAD

**Issue by cruxxxxxx** [bubble2k16/snes9x_3ds#17]
Hey, great work on this emulator! It's made my first play through of Earthbound awesome. I had an idea for a feature, which I'd like to implement, but I was wondering if it'd make it to the official release or just be a fork?

Something like a "Save Sync" option where you input Dropbox credentials and use ctrulib to upload/download the save files/savestates. Seems pretty doable. 

What do you think? Would those saves/save states work on desktop snes9x?

Best,
Mike

**Comment by bubble2k16** [comment]
Sounds a bit complicated because that would mean integrating with Dropbox's OAuth authentication (it's a secure way to allow users to login, usually with the use of a browser); it will be painful to have to do this from scratch on the 3DS and to constantly upkeep this if the OAuth version changes.

So nope, sorry, I won't add this. :)
