### ISSUE TITLE
Screen remains black when put into sleep mode

### ISSUE THREAD

**Issue by ghost** [bubble2k16/snes9x_3ds#20]
If I close the screen after exiting from a game into the home menu of the 3ds, the screen stays black when I turn it on forcing me to restart the 3ds, can you fix that.

**Comment by AdmiralCurtiss** [comment]
It took me a bit to figure out what this means, but now I just ran into it so I can confirm.

Using the installed CIA version, pause the app with Home, then on the Home screen, without exiting the app, close (as in, physically shut) the system. The system will not properly enter sleep mode and freeze.

**Comment by ghost** [comment]
Yes, that's my problem, any idea how to fix it?

**Comment by AdmiralCurtiss** [comment]
FYI this doesn't happen when compiling with ctrulib 1.2.0, but that introduces another issue where closing the app crashes the system. It still doesn't seem quite right though, since even with ctrulib 1.2.0, going into sleep mode on the Home screen keeps the power light at full brightness instead of dimming it.

Anyway, other homebrew apps (eg. FBI) behave the same way, so I think this is a ctrulib issue, not a snes9x_3ds issue.

**Comment by ghost** [comment]
. . . sorry, I didn't quite understand that, so what am I suppose to do?

**Comment by AdmiralCurtiss** [comment]
Unless you're a programmer, I don't think you can do anything about this. Don't close your system while snes9x_3ds is suspended and wait for someone else to fix this issue.
