### ISSUE TITLE
[Request] Either Blargg's or Anomie's S-SMP for N3DS users

### ISSUE THREAD

**Issue by roflcopter777** [bubble2k16/snes9x_3ds#55]
**Here are the current Snes emulators for N3DS users:**
Snes9x for 3DS*
Snes9x 2002*
Snes9x 2005*
Snes9x 2005 Plus
Snes9x 2010
BlargSnes*

* Primarily to substitute the lack of Snes VC on old 3DS models, due to the weaker CPU. 

**Current situation:**
Currently, Snes9x 2005 Plus and 2010 are severely bottle-necked by the S-SMP core used in snes9x 1.52..On the other hand, the Snes VC has more accurate sound than iterations of Snes9x 2005 and below (versions 1.43, 1.51, don't have the accurate sound), and sounds on par with at least Anomie's S-SMP. 

**So here's the rundown:**
Is it possible have a branch (for N3DS/N2DS XL users) of Snes9x 1.43, implemented with Anomie's audio and have it optimized with minimal performance degradation?? Some games are completely broken with no sound effects, Earthworm Jim 2 streams SPC700 data, and as such, only a few emulators play it correctly.  Either Blargg's or Anomie's audio core? Nintendo optimized their emulators, so surely, the N3DS surely is powerful enough to handle full speed and better audio,  

I can provide some information showing comparative audio samples taken from Snes9x 1.51, 1.52, etc to show what I  mean by games that require a certain S-SMP core to have full audio.  Would this be better suited towards Bountysource in hopes of garnering more attention? Thank you for your time.

**Comment by bubble2k16** [comment]
The original intention was have this run on the Old 3DS. Already this Snes9x for 3DS version is translated with the Snes9x v1.51 sound core (even when the more CPU core is the Snes9x v1.43 version).

Also I don't wish to duplicate what work has been done before in the Retroarch versions. Writing an audio engine that runs fast and accurate on the New 3DS will require significant amounts of time that I won't invest in. So I'm sorry, but I won't heading that direction. :) 

You can try asking anywhere else to see if anyone is willing to pick it up. But I'd suggest that it be a branch from the Snes9x 2010 cores since it's probably the most accurate in everything than a branch from Snes9x for 3DS.

**Comment by roflcopter777** [comment]
I'm not even going to bother asking anyone else, because there's no interest. And since I've gotten an Snes Classic, my interest in 3DS homebrew has deteriorated -_-

**Comment by roflcopter777** [comment]
FYI, I'm saying this because it's true, no one else is interested in this very specific request, 
I sure as heck don't know any dev willing to do this, even with a BountySource
